// Bilingual UI dictionary for SMC Liquidity Hunting AI Lab dashboard.
const I18N = {
  en: {
    title: 'SMC Liquidity Hunting AI Lab',
    subtitle: 'Institutional Forex & Gold (XAUUSD) Signals',
    signals_heading: 'Latest Signals',
    entry: 'Entry',
    stop_loss: 'Stop Loss',
    take_profit: 'Take Profit',
    max_lot: 'Max Lot',
    volatility: 'Volatility',
    status: 'Status',
    no_signals: 'No signals published yet. Check back before the next session.',
    footer_note: 'Signals are generated by an AI agent using Smart Money Concepts. Trade at your own risk — never exceed the stated lot size.',
    lang_button: 'বাংলা'
  },
  bn: {
    title: 'এসএমসি লিকুইডিটি হান্টিং এআই ল্যাব',
    subtitle: 'ইনস্টিটিউশনাল ফরেক্স ও গোল্ড (XAUUSD) সিগন্যাল',
    signals_heading: 'সর্বশেষ সিগন্যালসমূহ',
    entry: 'এন্ট্রি',
    stop_loss: 'স্টপ লস',
    take_profit: 'টেক প্রফিট',
    max_lot: 'সর্বোচ্চ লট',
    volatility: 'ভলাটিলিটি',
    status: 'স্ট্যাটাস',
    no_signals: 'এখনও কোনো সিগন্যাল প্রকাশিত হয়নি। পরের সেশনের আগে আবার দেখুন।',
    footer_note: 'সিগন্যালগুলো স্মার্ট মানি কনসেপ্ট ব্যবহার করে একটি এআই এজেন্ট তৈরি করে। নিজ ঝুঁকিতে ট্রেড করুন — নির্দেশিত লট সাইজ কখনো অতিক্রম করবেন না।',
    lang_button: 'English'
  }
};
